common:
  recordEnable: false
  singleTrial: false
  initRandomAgentPosition: true

resources:
  numResourceFood: 5 # 50
  numResourceWater: 0 # 50
  numResourcePond: 1
  resourceFoodValue: 3
  resourceWaterValue: 3

  IsRandomFoodPosition: true
  IsRandomWaterPosition: true
  IsRandomPondPosition: false

  # pondResourcePositionsX: -19
  # pondResourcePositionsY: -9.7
  # pondResourcePositionsZ: -14

  minDistanceToPond: 50
  randomPositionMaxTry: 100

fieldtemperature:
  numberOfGridCubeX: 100
  numberOfGridCubeZ: 100
  sizeOfGridCubeX: 1
  sizeOfGridCubeY: 5
  sizeOfGridCubeZ: 1
  positionOfGridCenterX: -25
  positionOfGridCenterY: 0
  positionOfGridCenterZ: -25

  useObjectHotSpot: false
  useRandomHotSpot: true

  fieldDefaultTemp: -20
  hotSpotCount: 20
  hotSpotTemp: 20
  smoothingSigma: 12

  heatMapMaxTemp: 15
  heatMapMinTemp: -15

  dayNightSpeed: 0
  dayTemperatureVariance: 0
  nightTemperatureVariance: -20

action:
  moveSpeed: 12
  turnSpeed: 800
  autoEat: 0
  eatingDistance: 1

ev:
  maxFoodLevel: 15
  minFoodLevel: -15
  changeFood_0: -0.02 #0.2
  startFoodLevel: 0

  maxWaterLevel: 15
  minWaterLevel: -15
  changeWater_0: -0.01 #0.2
  startWaterLevel: 0

  maxThermoLevel: 15
  minThermoLevel: -15
  changeBody_0: 0.01 #-0.001
  startThermoLevel: 0

visualSensor:
  useVisual: true
  visualHight: 64
  visualWidth: 64

olfactorySensor:
  useOlfactory: true
  olfactorySensorLength: 100
  olfactoryFeatureSize: 10

thermoSensor:
  useThermo: true
  thermoSensorChangeRate: 10
  thermoSensorSize: 8

touchSensor:
  useTouchObs: true
